set identity_insert PRODUTOS_MATERIAS_PRIMAS on;

INSERT INTO PRODUTOS_MATERIAS_PRIMAS (ID, CODMATERIA_PRIMA, CODPRODUTO, QTDE)  VALUES (1, 2, 1, 1);
INSERT INTO PRODUTOS_MATERIAS_PRIMAS (ID, CODMATERIA_PRIMA, CODPRODUTO, QTDE)  VALUES (2, 3, 1, 3);
INSERT INTO PRODUTOS_MATERIAS_PRIMAS (ID, CODMATERIA_PRIMA, CODPRODUTO, QTDE)  VALUES (3, 5, 1, 10);

set identity_insert PRODUTOS_MATERIAS_PRIMAS off;
