
set identity_insert [PRODUTOS] on

INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (1, 'Arroz', 1, '2014-03-02', 0, 1, '21:11:35', '2014-02-07 21:11:42', 5, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (2, 'Feijão', 1, '2014-02-07', 0, 250.23, NULL, NULL, 2, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (3, 'Tomate Seco', 1, '2014-02-07', 0, 2, NULL, NULL, 3, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (4, 'Macarrão', 1, '2014-02-07', 0, 5, NULL, NULL, 4, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (5, 'Cebola', 1, '2014-02-07', 0, 6, NULL, NULL, 5, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (6, 'Salsa', 1, '2014-02-07', 0, 2, NULL, NULL, 1, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (7, 'Repolho', 1, '2014-02-07', 0, 5, NULL, NULL, 2, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (8, 'Manjericão', 0, '2014-02-07', 0, 6, NULL, NULL, 3, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (9, 'Batata', 1, '2014-02-07', 0, 7, NULL, NULL, 4, 'S', 'P');
INSERT INTO PRODUTOS (CODPRODUTO, DESCRICAO, ATIVO, DATA_CADASTRO, CODTIPO_PRODUTO, PRECO_VENDA, HORACADASTRO, DATAHORACADASTRO, CODUNIDADE, ATIVO_STR, TIPO_PRODUTO) VALUES (113, 'Arroz Integral 02/03/2014 19:55:57:449', 1, '2014-03-02', 0, 12563.21, '21:11:35', '2014-02-07 21:11:42', 5, 'S', 'P');

set identity_insert [PRODUTOS] off

COMMIT WORK;
