set identity_insert [unidades] on

INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO, RESUMIDA, ATIVO) VALUES (1, 'Unidade', 'UN', 1);
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO, RESUMIDA, ATIVO) VALUES (2, 'Peças', 'PÇ', 1);
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO, RESUMIDA, ATIVO) VALUES (3, 'Litros', 'LT', 1);
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO, RESUMIDA, ATIVO) VALUES (4, 'Metros', 'M', 1);
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO, RESUMIDA, ATIVO) VALUES (5, 'Milímetros', 'MM', 1);
INSERT INTO UNIDADES (CODUNIDADE, DESCRICAO, RESUMIDA, ATIVO) VALUES (6, 'Kilogramas', 'KG', 1);

set identity_insert [unidades] off

COMMIT WORK;
